server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route #payment_route,路由ID,没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
        - id: payment_route2 #payment_route,路由ID,没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对其牛头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb/**  #断言，路径相匹配的进行路由
#            - After=2020-05-10T15:25:50.231+08:00[Asia/Shanghai]
#            - Cookie=username,dsp #测试地址：curl http://localhost:9527/payment/lb --cookie "username=dsp"
#            - Header=X-Request-Id,\d+ #请求头要有X-request-Id属性并且值为整数的正则 测试地址：curl http://localhost:9527/payment/lb -H "X-Request-Id:1"
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka